<?php include 'include/header.php';  ?>
<div class="container">
                      <table class="table">
                        <thead>
                          <tr>
                          	<th>ID</th>
                            <th>From</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>To</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Seats</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <td>1</td>
                            <td>USA</td>
                            <td>12-3-2016</td>
                            <td>20:30</td>
                            <td>UK</td>
                            <td>13-3-2016</td>
                            <td>3:00</td>
                            <td>141</td>
                          </tr>
                          <tr>
                            <td>2</td>
                            <td>Egypt</td>
                            <td>22-3-2016</td>
                            <td>12:30</td>
                            <td>Japan</td>
                            <td>25-3-2016</td>
                            <td>17:00</td>
                            <td>532</td>
                          </tr>
                          <tr>
                          	<td>3</td>
                            <td>France</td>
                            <td>27-3-2016</td>
                            <td>20:30</td>
                            <td>Egypt</td>
                            <td>4-4-2016</td>
                            <td>3:00</td>
                            <td>1102</td>
                          </tr>
                        </tbody>
                      </table>
</div>